##
##  Makefile -- Build procedure for sample wodan2 Apache module
##  Autogenerated via ``apxs -n wodan2 -g''.
##

builddir=.
top_srcdir=/Users/ilja/apache2
top_builddir=/Users/ilja/apache2
include /Users/ilja/apache2/build/special.mk

#   the used tools
APXS=apxs
APACHECTL=apachectl

#   additional defines, includes and libraries
#DEFS=-Dmy_define=my_value
#INCLUDES=-Imy/include/dir
#LIBS=-Lmy/lib/dir -lmylib

#   the default target
all: local-shared-build

#   install the shared object file into Apache 
install: install-modules

#   cleanup
clean:
	-rm -f mod_wodan2.o mod_wodan2.lo mod_wodan2.slo mod_wodan2.la 

#   simple test
test: reload
	lynx -mime_header http://localhost/wodan2

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

