/* 
**  mod_wodan2.c -- Apache sample wodan2 module
**  [Autogenerated via ``apxs -n wodan2 -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_wodan2.c
**
**  Then activate it in Apache's httpd.conf file for instance
**  for the URL /wodan2 in as follows:
**
**    #   httpd.conf
**    LoadModule wodan2_module modules/mod_wodan2.so
**    <Location /wodan2>
**    SetHandler wodan2
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /wodan2 and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/wodan2 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**  
**    The sample page from mod_wodan2.c
*/ 

#define WODAN_NAME "Wodan2"
#define WODAN_VERSION "0.1"

/* local includes */
#include "datatypes.h"

/* Apache includes */
#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"
#include "apr_strings.h"



/* initialize Wodan2 */
static int wodan2_init_handler(apr_pool_t *p, apr_pool_t *plog, apr_pool_t *ptemp,
	server_rec *s)
{
	const char *identifier_string;
	
	identifier_string = apr_psprintf(p, "%s/%s", WODAN_NAME, WODAN_VERSION);
	ap_add_version_component(p, identifier_string);
	
	return OK;
}                          

/* create a new config struct. We keep it very simple, by initializing 
 * everything to zero. Only create some arrays, because we'll need them
 * later on
 */
static void *wodan2_create_config(apr_pool_t *p)
{
	wodan_reverseproxy_config_t* config = (wodan_reverseproxy_config_t*) 
		ap_pcalloc(p, sizeof(wodan_reverseproxy_config_t));
	
	config->cachedir_levels = DEFAULT_CACHEDIR_LEVELS;
	config->reverseproxypasses = apr_array_make(p, 0, 
		sizeof(wodan_proxy_destination_t));
	config->reverseproxypassesreverse = apr_array_make(p, 0,
		sizeof(wodan_proxy_alias_t));
	config->defaultcachetimes = apr_array_make(p, 0,
		sizeof(wodan_default_cachetime_t));
	config->defaultcachetimes_regex = apr_array_make(p, 0,
		sizeof(wodan_default_cachetime_regex_t));
	config->defaultcachetimes_header = apr_array_make(p, 0,
		sizeof(wodan_default_cachetime_header_t));	
	return config;		
}

static void *wodan2_create_server_config(apr_pool_t *p, server_rec *s)
{
	return wodan2_create_config(p);
}

static void *wodan2_create_dir_config(apr_pool_t *p, char *dir)
{
	return wodan2_create_config(p);
}
	                         
/* The sample content handler */
static int wodan2_handler(request_rec *r)
{
    if (strcmp(r->handler, "wodan2")) {
        return DECLINED;
    }
    r->content_type = "text/html";      

    if (!r->header_only)
        ap_rputs("The sample page from mod_wodan2.c\n", r);
    return OK;
}

static void wodan2_register_hooks(apr_pool_t *p)
{
	ap_hook_post_config(wodan2_init_handler, NULL, NULL, APR_HOOK_MIDDLE);
    ap_hook_handler(wodan2_handler, NULL, NULL, APR_HOOK_MIDDLE);
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA wodan2_module = {
    STANDARD20_MODULE_STUFF, 
    wodan2_create_dir_config,   /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    wodan2_create_server_config,/* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    NULL,                  /* table of config file commands       */
    wodan2_register_hooks  /* register hooks                      */
};

